Repository SallyHaefling/color-catcher-frontend, pull requests merged in 2019-07, with the labels that each got.

#24 Lock colors
  src/actions/index.js
  src/components/Header/Header.js
  src/components/Palettes/Palettes.js
  src/components/Palettes/_Palettes.scss
  src/components/Palettes/_Palettes.test.js
  src/containers/App/App.js
  src/containers/Header/Header.js
  src/containers/Header/Header.test.js
  src/containers/Header/_Header.scss
  src/containers/Swatch/Swatch.js
  src/reducers/palette-reducer.js
Labels: Essential

#26 Setup tests actions reducers
  package-lock.json
  package.json
  setupTests.js
  src/actions/index.test.js
  src/reducers/palette-reducer.js
  src/reducers/palette-reducer.test.js
  src/reducers/project-reducer.test.js
Labels: Essential, Testing

#32 Delete single palette from project
  src/actions/index.js
  src/components/Palettes/Palettes.js
  src/reducers/palettes-reducer.js
Labels: Essential

#35 Delete button
  src/components/Palettes/Palettes.js
  src/components/Palettes/_Palettes.scss
  src/reducers/palettes-reducer.test.js
  src/reducers/project-reducer.test.js
  src/reducers/projects-reducer.test.js
Labels: Essential

#38 Delete button
  src/components/Palettes/Palettes.js
Labels: Essential

#39 Style layout text
  public/index.html
  src/components/Palettes/Palettes.js
  src/components/Palettes/_Palettes.scss
  src/components/Projects/Projects.js
  src/components/Projects/_Projects.scss
  src/containers/Header/Header.js
  src/containers/Header/_Header.scss
  src/containers/Swatch/Swatch.js
  src/containers/Swatch/_Swatch.scss
Labels: enhancement

#41 Fix palette reducer test
  src/reducers/palette-reducer.test.js
Labels: Testing
